export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Chetan Kumar",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Pawan Sah",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Kartik Wadhwa",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Cry Foundation",
  },
  {
    id:5,
    profilePicture: "assets/person/8.jpeg",
    username: "Aditya Gaur",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Thomas Holden",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Kristen Bennett",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "I think that People forget about Swacch bharat abhiyan...",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc:"Donate old books for poor kids",
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc:"Follow our facebook page.  Join us !!",
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc:"Donate old cloths",
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc:"Love For All, Hatred For None.",
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 1,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 2,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc:"Follow our Social Verse page on Facebook.",
    photo: "",
    date: "1 week ago",
    userId: 3,
    like: 104,
    comment: 12,
  },
];
